services:
  app:
    image: ghcr.io/inferst/evotars-app/app:main
    container_name: evotars-app
    working_dir: /app
    environment:
      - HOST_URL=${HOST_URL}
      - ADMIN_URL=${ADMIN_URL}
      - CLIENT_URL=${CLIENT_URL}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CALLBACK_URL=${TWITCH_CALLBACK_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    user: $DOCKER_USER
    restart: unless-stopped

  website:
    image: ghcr.io/inferst/evotars-app/website:main
    environment:
      - PORT=${REMIX_PORT}
    container_name: evotars-website
    working_dir: /app
    user: $DOCKER_USER
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: evotars-postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dudes
      - POSTGRES_USER=dudes
      - POSTGRES_DB=dudes
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: evotars-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/html
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  default:
    external: true
    name: scoobydoo
